import type {
  Outage,
  SafetyPin,
  ServiceLocation,
  WaitCheckin,
} from "@/lib/supabase/types";

const now = () => new Date();
const minutesAgo = (m: number) =>
  new Date(now().getTime() - m * 60 * 1000).toISOString();
const hoursAhead = (h: number) =>
  new Date(now().getTime() + h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) =>
  new Date(now().getTime() - d * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_OUTAGES: Outage[] = [
  {
    id: "o-1",
    utility: "water",
    status: "active",
    area_name: "8 Noyabr küç., 12-24 evlər",
    center_lat: 40.4101,
    center_lng: 49.8612,
    radius_m: 350,
    started_at: minutesAgo(85),
    estimated_end: hoursAhead(2),
    resolved_at: null,
    source: "azersu",
    source_url: null,
    description:
      "Magistral xəttdə qəza təmiri. Su təchizatı müvəqqəti dayandırılıb.",
    created_at: minutesAgo(85),
  },
  {
    id: "o-2",
    utility: "electricity",
    status: "active",
    area_name: "Ziya Bünyadov pr., metro yaxınlığı",
    center_lat: 40.4053,
    center_lng: 49.8587,
    radius_m: 420,
    started_at: minutesAgo(38),
    estimated_end: hoursAhead(1.3),
    resolved_at: null,
    source: "azerisiq",
    source_url: null,
    description:
      "Transformator yarımstansiyasında qəza. Briqada yerdədir.",
    created_at: minutesAgo(38),
  },
  {
    id: "o-3",
    utility: "gas",
    status: "active",
    area_name: "Ağa Nemətulla küç., 18 saylı bina",
    center_lat: 40.4012,
    center_lng: 49.8551,
    radius_m: 220,
    started_at: minutesAgo(12),
    estimated_end: hoursAhead(3),
    resolved_at: null,
    source: "socar",
    source_url: null,
    description:
      "Qaz sızıntısı barəsində bildirim. Sahə blokiranır, ekspert briqadası yola düşüb.",
    created_at: minutesAgo(12),
  },
  {
    id: "o-4",
    utility: "water",
    status: "planned",
    area_name: "Tələbə qəsəbəsi, 3-cü mikrorayon",
    center_lat: 40.4163,
    center_lng: 49.8688,
    radius_m: 600,
    started_at: hoursAhead(14),
    estimated_end: hoursAhead(20),
    resolved_at: null,
    source: "azersu",
    source_url: null,
    description:
      "Planlı texniki iş. Sabah 08:00-14:00 arası su olmayacaq.",
    created_at: minutesAgo(180),
  },
  {
    id: "o-5",
    utility: "electricity",
    status: "resolved",
    area_name: "Qara Qarayev m. ərazisi",
    center_lat: 40.4022,
    center_lng: 49.8731,
    radius_m: 380,
    started_at: minutesAgo(300),
    estimated_end: minutesAgo(120),
    resolved_at: minutesAgo(120),
    source: "azerisiq",
    source_url: null,
    description: "Elektrik şəbəkəsində nasazlıq. Bərpa edilib.",
    created_at: minutesAgo(300),
  },
  {
    id: "o-6",
    utility: "water",
    status: "resolved",
    area_name: "28 May küç.",
    center_lat: 40.3987,
    center_lng: 49.8451,
    radius_m: 280,
    started_at: minutesAgo(480),
    estimated_end: minutesAgo(240),
    resolved_at: minutesAgo(240),
    source: "azersu",
    source_url: null,
    description: "Boru zədəsi aradan qaldırıldı.",
    created_at: minutesAgo(480),
  },
];

export const MOCK_LOCATIONS: ServiceLocation[] = [
  {
    id: "loc-1",
    name: "ASAN Xidmət Mərkəzi №1",
    kind: "asan",
    lat: 40.4087,
    lng: 49.8554,
    address: "Nərimanov, Atatürk pr. 90",
    opens_at: "09:00",
    closes_at: "20:00",
  },
  {
    id: "loc-2",
    name: "Nərimanov Rayon İcra Hakimiyyəti",
    kind: "rih",
    lat: 40.4068,
    lng: 49.8612,
    address: "Nərimanov, Ağa Nemətulla 4",
    opens_at: "09:00",
    closes_at: "18:00",
  },
  {
    id: "loc-3",
    name: "1 saylı Şəhər Poliklinikası",
    kind: "poliklinika",
    lat: 40.4124,
    lng: 49.8651,
    address: "Nərimanov, 8 Noyabr 14",
    opens_at: "08:00",
    closes_at: "20:00",
  },
  {
    id: "loc-4",
    name: "3 saylı Poliklinika",
    kind: "poliklinika",
    lat: 40.4045,
    lng: 49.8702,
    address: "Nərimanov, Ziya Bünyadov 32",
    opens_at: "08:00",
    closes_at: "20:00",
  },
  {
    id: "loc-5",
    name: "21 saylı Uşaq Poliklinikası",
    kind: "poliklinika",
    lat: 40.4002,
    lng: 49.8489,
    address: "Nərimanov, Bakıxanov 8",
    opens_at: "08:00",
    closes_at: "19:00",
  },
  {
    id: "loc-6",
    name: "Nərimanov Poçt Şöbəsi №1",
    kind: "post",
    lat: 40.4061,
    lng: 49.8595,
    address: "Nərimanov, Ağa Nemətulla 12",
    opens_at: "09:00",
    closes_at: "18:00",
  },
  {
    id: "loc-7",
    name: "Nərimanov Poçt Şöbəsi №2",
    kind: "post",
    lat: 40.4115,
    lng: 49.873,
    address: "Nərimanov, Tələbə qəsəbəsi",
    opens_at: "09:00",
    closes_at: "18:00",
  },
  {
    id: "loc-8",
    name: "Kapital Bank — Nərimanov filialı",
    kind: "bank",
    lat: 40.4076,
    lng: 49.858,
    address: "Nərimanov, Atatürk pr. 78",
    opens_at: "09:30",
    closes_at: "17:30",
  },
];

const waitTuples: Array<[string, number, number]> = [
  ["loc-1", 8, 6],
  ["loc-1", 12, 18],
  ["loc-1", 10, 24],
  ["loc-1", 15, 41],
  ["loc-1", 22, 55],
  ["loc-1", 18, 72],
  ["loc-3", 25, 4],
  ["loc-3", 35, 19],
  ["loc-3", 40, 38],
  ["loc-3", 28, 67],
  ["loc-4", 15, 9],
  ["loc-4", 12, 22],
  ["loc-4", 20, 48],
  ["loc-5", 8, 11],
  ["loc-5", 14, 33],
  ["loc-6", 5, 7],
  ["loc-6", 12, 26],
  ["loc-6", 8, 51],
  ["loc-7", 18, 14],
  ["loc-7", 22, 39],
  ["loc-7", 15, 88],
  ["loc-8", 22, 5],
  ["loc-8", 28, 28],
  ["loc-8", 35, 62],
];

export const MOCK_WAITS: WaitCheckin[] = waitTuples.map(
  ([loc, wm, mins], i) => ({
    id: `w-${i}`,
    location_id: loc,
    user_id: null,
    wait_minutes: wm,
    reported_at: minutesAgo(mins),
  })
);

export const MOCK_PINS: SafetyPin[] = [
  {
    id: "p-1",
    user_id: null,
    lat: 40.4096,
    lng: 49.8623,
    category: "lighting",
    description:
      "Atatürk prospektində bir neçə işıq dirəyi sönükdür, axşam saatlarında piyada keçidi qaranlıq qalır.",
    photo_url: null,
    upvotes: 14,
    status: "pending",
    created_at: daysAgo(2),
  },
  {
    id: "p-2",
    user_id: null,
    lat: 40.4042,
    lng: 49.8589,
    category: "crossing",
    description:
      "Piyada keçidində xətlər tamamilə silinib, sürücülər görmür. Çox təhlükəlidir.",
    photo_url: null,
    upvotes: 22,
    status: "pending",
    created_at: daysAgo(3),
  },
  {
    id: "p-3",
    user_id: null,
    lat: 40.4127,
    lng: 49.8665,
    category: "traffic",
    description:
      "İşıqfor xarabdır, axşamlar çox təhlükəlidir. Avtomobillər kəsişməni anlamadan keçir.",
    photo_url: null,
    upvotes: 31,
    status: "reviewed",
    created_at: daysAgo(5),
  },
  {
    id: "p-4",
    user_id: null,
    lat: 40.4011,
    lng: 49.8513,
    category: "sidewalk",
    description: "Səki blokları sınıb, qoca qadın bu yaxınlarda büdrədi.",
    photo_url: null,
    upvotes: 7,
    status: "pending",
    created_at: minutesAgo(18 * 60),
  },
  {
    id: "p-5",
    user_id: null,
    lat: 40.4067,
    lng: 49.8702,
    category: "lighting",
    description: "Həyət içində LED işıq lazımdır, tamamilə qaranlıqdır.",
    photo_url: null,
    upvotes: 11,
    status: "pending",
    created_at: daysAgo(1),
  },
  {
    id: "p-6",
    user_id: null,
    lat: 40.4153,
    lng: 49.8718,
    category: "crossing",
    description:
      "Məktəb yaxınlığında piyada keçidi yoxdur, uşaqlar yolu xaotik şəkildə keçir.",
    photo_url: null,
    upvotes: 28,
    status: "pending",
    created_at: daysAgo(4),
  },
  {
    id: "p-7",
    user_id: null,
    lat: 40.3998,
    lng: 49.8456,
    category: "traffic",
    description:
      "Tıxac problemi səhər 8:00-9:00 arası dəhşətlidir. Qovşaqda nizamlama lazımdır.",
    photo_url: null,
    upvotes: 9,
    status: "pending",
    created_at: minutesAgo(6 * 60),
  },
  {
    id: "p-8",
    user_id: null,
    lat: 40.4032,
    lng: 49.8645,
    category: "other",
    description: "Açıq lyuk qapağı! Cəld bağlanmalıdır.",
    photo_url: null,
    upvotes: 19,
    status: "resolved",
    created_at: daysAgo(10),
  },
  {
    id: "p-9",
    user_id: null,
    lat: 40.4088,
    lng: 49.8551,
    category: "lighting",
    description: "Park ərazisində gecə işıqlandırma yox dərəcəsindədir.",
    photo_url: null,
    upvotes: 6,
    status: "pending",
    created_at: minutesAgo(8 * 60),
  },
  {
    id: "p-10",
    user_id: null,
    lat: 40.4119,
    lng: 49.8589,
    category: "sidewalk",
    description:
      "Səki dar və avtomobillər səkiyə çıxır, anaların əli arabalı kənardan keçməyə məcburdur.",
    photo_url: null,
    upvotes: 13,
    status: "pending",
    created_at: daysAgo(2),
  },
  {
    id: "p-11",
    user_id: null,
    lat: 40.4055,
    lng: 49.8521,
    category: "crossing",
    description:
      'Piyada keçidində "yavaş" işarəsi yoxdur, sürücülər tam sürətlə keçir.',
    photo_url: null,
    upvotes: 4,
    status: "pending",
    created_at: minutesAgo(4 * 60),
  },
  {
    id: "p-12",
    user_id: null,
    lat: 40.4012,
    lng: 49.8678,
    category: "other",
    description:
      "Zibil qutusu tam doludur, ətrafa səpələnir. Həm gözəgəlimsiz, həm sanitariya problemi.",
    photo_url: null,
    upvotes: 8,
    status: "pending",
    created_at: minutesAgo(14 * 60),
  },
];
