import type {
  Outage,
  SafetyPin,
  ServiceLocation,
  WaitCheckin,
} from "./types";

const minutesAgo = (m: number) =>
  new Date(Date.now() - m * 60 * 1000).toISOString();
const hoursAhead = (h: number) =>
  new Date(Date.now() + h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) =>
  new Date(Date.now() - d * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_OUTAGES: Outage[] = [
  {
    id: "o-1",
    utility: "water",
    status: "active",
    area_name: "8 Noyabr küç., 12-24 evlər",
    center_lat: 40.4101,
    center_lng: 49.8612,
    radius_m: 350,
    started_at: minutesAgo(85),
    estimated_end: hoursAhead(2),
    resolved_at: null,
    source: "azersu",
    source_url: null,
    description: "Magistral xəttdə qəza təmiri.",
    created_at: minutesAgo(85),
  },
  {
    id: "o-2",
    utility: "electricity",
    status: "active",
    area_name: "Ziya Bünyadov pr., metro yaxınlığı",
    center_lat: 40.4053,
    center_lng: 49.8587,
    radius_m: 420,
    started_at: minutesAgo(38),
    estimated_end: hoursAhead(1.3),
    resolved_at: null,
    source: "azerisiq",
    source_url: null,
    description: "Transformator yarımstansiyasında qəza.",
    created_at: minutesAgo(38),
  },
  {
    id: "o-3",
    utility: "gas",
    status: "active",
    area_name: "Ağa Nemətulla küç., 18 saylı bina",
    center_lat: 40.4012,
    center_lng: 49.8551,
    radius_m: 220,
    started_at: minutesAgo(12),
    estimated_end: hoursAhead(3),
    resolved_at: null,
    source: "socar",
    source_url: null,
    description: "Qaz sızıntısı barəsində bildirim.",
    created_at: minutesAgo(12),
  },
  {
    id: "o-4",
    utility: "water",
    status: "planned",
    area_name: "Tələbə qəsəbəsi, 3-cü mikrorayon",
    center_lat: 40.4163,
    center_lng: 49.8688,
    radius_m: 600,
    started_at: hoursAhead(14),
    estimated_end: hoursAhead(20),
    resolved_at: null,
    source: "azersu",
    source_url: null,
    description: "Planlı texniki iş. Sabah 08:00-14:00.",
    created_at: minutesAgo(180),
  },
];

export const MOCK_LOCATIONS: ServiceLocation[] = [
  {
    id: "loc-1",
    name: "ASAN Xidmət №1",
    kind: "asan",
    lat: 40.4087,
    lng: 49.8554,
    address: "Atatürk pr. 90",
    opens_at: "09:00",
    closes_at: "20:00",
  },
  {
    id: "loc-2",
    name: "Nərimanov RİH",
    kind: "rih",
    lat: 40.4068,
    lng: 49.8612,
    address: "Ağa Nemətulla 4",
    opens_at: "09:00",
    closes_at: "18:00",
  },
  {
    id: "loc-3",
    name: "1 saylı Şəhər Poliklinikası",
    kind: "poliklinika",
    lat: 40.4124,
    lng: 49.8651,
    address: "8 Noyabr 14",
    opens_at: "08:00",
    closes_at: "20:00",
  },
  {
    id: "loc-4",
    name: "3 saylı Poliklinika",
    kind: "poliklinika",
    lat: 40.4045,
    lng: 49.8702,
    address: "Ziya Bünyadov 32",
    opens_at: "08:00",
    closes_at: "20:00",
  },
  {
    id: "loc-5",
    name: "Nərimanov Poçt №1",
    kind: "post",
    lat: 40.4061,
    lng: 49.8595,
    address: "Ağa Nemətulla 12",
    opens_at: "09:00",
    closes_at: "18:00",
  },
  {
    id: "loc-6",
    name: "Kapital Bank — Nərimanov",
    kind: "bank",
    lat: 40.4076,
    lng: 49.858,
    address: "Atatürk pr. 78",
    opens_at: "09:30",
    closes_at: "17:30",
  },
];

const tuples: Array<[string, number, number]> = [
  ["loc-1", 8, 6],
  ["loc-1", 12, 18],
  ["loc-1", 22, 55],
  ["loc-3", 25, 4],
  ["loc-3", 35, 19],
  ["loc-3", 40, 38],
  ["loc-4", 15, 9],
  ["loc-4", 12, 22],
  ["loc-5", 5, 7],
  ["loc-5", 12, 26],
  ["loc-6", 22, 5],
  ["loc-6", 28, 28],
];

export const MOCK_WAITS: WaitCheckin[] = tuples.map(([loc, wm, mins], i) => ({
  id: `w-${i}`,
  location_id: loc,
  user_id: null,
  wait_minutes: wm,
  reported_at: minutesAgo(mins),
}));

export const MOCK_PINS: SafetyPin[] = [
  {
    id: "p-1",
    user_id: null,
    lat: 40.4096,
    lng: 49.8623,
    category: "lighting",
    description:
      "Atatürk prospektində bir neçə işıq dirəyi sönükdür, axşam keçidi qaranlıqdır.",
    photo_url: null,
    upvotes: 14,
    status: "pending",
    created_at: daysAgo(2),
  },
  {
    id: "p-2",
    user_id: null,
    lat: 40.4042,
    lng: 49.8589,
    category: "crossing",
    description: "Piyada keçidində xətlər tamamilə silinib.",
    photo_url: null,
    upvotes: 22,
    status: "pending",
    created_at: daysAgo(3),
  },
  {
    id: "p-3",
    user_id: null,
    lat: 40.4127,
    lng: 49.8665,
    category: "traffic",
    description: "İşıqfor xarabdır, axşamlar çox təhlükəlidir.",
    photo_url: null,
    upvotes: 31,
    status: "reviewed",
    created_at: daysAgo(5),
  },
  {
    id: "p-4",
    user_id: null,
    lat: 40.4011,
    lng: 49.8513,
    category: "sidewalk",
    description: "Səki blokları sınıb.",
    photo_url: null,
    upvotes: 7,
    status: "pending",
    created_at: minutesAgo(18 * 60),
  },
  {
    id: "p-5",
    user_id: null,
    lat: 40.4153,
    lng: 49.8718,
    category: "crossing",
    description: "Məktəb yaxınlığında piyada keçidi yoxdur.",
    photo_url: null,
    upvotes: 28,
    status: "pending",
    created_at: daysAgo(4),
  },
];
